clear;
clc;
close all;

pre_dir  = 'C:\MATLAB\focused-attention-meditation-eeg-analysis\data\sub-001\pre';
post_dir = 'C:\MATLAB\focused-attention-meditation-eeg-analysis\data\sub-001\post';

% Pre MW
pre_MW_EEG = pop_loadset( ...
    'filename', 'sub-001_ses-premedita_task-restCE01_eeg_preproc_icrm.set', ...
    'filepath', pre_dir);

% Pre MF
pre_MF_EEG = pop_loadset( ...
    'filename', 'sub-001_ses-premedita_task-slMedita_eeg_preproc_icrm.set', ...
    'filepath', pre_dir);

% Post MW
post_MW_EEG = pop_loadset( ...
    'filename', 'sub-001_ses-posmedita_task-restCE01_eeg_preproc_icrm.set', ...
    'filepath', post_dir);

% Post MF
post_MF_EEG = pop_loadset( ...
    'filename', 'sub-001_ses-posmedita_task-slMedita_eeg_preproc_icrm.set', ...
    'filepath', post_dir);

%% 10秒エポックに分割

epoch_sec = 10;

pre_MW_epochs  = divide_epoches(pre_MW_EEG, epoch_sec);
pre_MF_epochs  = divide_epoches(pre_MF_EEG, epoch_sec);
post_MW_epochs = divide_epoches(post_MW_EEG, epoch_sec);
post_MF_epochs = divide_epoches(post_MF_EEG, epoch_sec);


%% サイズ確認

disp("Pre MW")
disp(size(pre_MW_epochs))

disp("Pre MF")
disp(size(pre_MF_epochs))

disp("Post MW")
disp(size(post_MW_epochs))

disp("Post MF")
disp(size(post_MF_epochs))


%% 原波形を保存

% 表示するエポック
ep = 1;

% 表示するチャネル
ch_range = 1:20;

% 保存先
save_dir = "figure";

plot_multichannel_wave( ...
    pre_MW_epochs, ...
    pre_MW_EEG, ...
    ep, ...
    ch_range, ...
    "Pre MW", ...
    save_dir);

plot_multichannel_wave( ...
    pre_MF_epochs, ...
    pre_MF_EEG, ...
    ep, ...
    ch_range, ...
    "Pre MF", ...
    save_dir);

plot_multichannel_wave( ...
    post_MW_epochs, ...
    post_MW_EEG, ...
    ep, ...
    ch_range, ...
    "Post MW", ...
    save_dir);

plot_multichannel_wave( ...
    post_MF_epochs, ...
    post_MF_EEG, ...
    ep, ...
    ch_range, ...
    "Post MF", ...
    save_dir);