%% 脳波データのスクロール表示（プロット）
% ※すでに「EEG」

pre_data_dir = ...
    'C:\MATLAB\focused-attention-meditation-eeg-analysis\data\sub-001\pre';

post_data_dir = ...
    'C:\MATLAB\focused-attention-meditation-eeg-analysis\data\sub-001\post';

% pre MF/MW
pre_MF = pop_loadset( ...
    'filename', 'sub-001_ses-premedita_task-slMedita_eeg_preproc_icrm.set', ...
    'filepath', pre_data_dir);

pre_MW = pop_loadset( ...
    'filename', 'sub-001_ses-premedita_task-restCE01_eeg_preproc_icrm.set', ...
    'filepath', pre_data_dir);

% post MF/MW
post_MF = pop_loadset( ...
    'filename', 'sub-001_ses-posmedita_task-slMedita_eeg_preproc_icrm.set', ...
    'filepath', post_data_dir);

post_MW = pop_loadset( ...
    'filename', 'sub-001_ses-posmedita_task-restCE01_eeg_preproc_icrm.set', ...
    'filepath', post_data_dir);

pop_eegplot( pre_MF, 1, 1, 1);
